### ISSUE TITLE
Can't use different languages/ Characters

### ISSUE THREAD

**Issue by Phagal** [Neocky/Text2McBook#2]
I tried copying a different language into the program, but it gives an error

  File "C:\Users\Sewak Singh Jabbal\Downloads\Text2McBook-v1.0.0\text2mcbook.py", line 11, in <module>
    text = f.read()
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 25: character maps to <undefined>

**Comment by Neocky** [comment]
Hey @Phagal,

the PR #4 should fix this issue.
I will close this issue.

Have a good day!
